name: CI — Build, Test & Docker

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

# --- BUILD ---
    - name: Docker build
      run: docker build -t thesnaxers:latest -f The-Snaxers/Dockerfile .

# --- DEPLOY (ACR PUSH) ---
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Tag and Push Docker image to ACR
      run: |
        docker tag thesnaxers:latest ${{ secrets.ACR_LOGIN_SERVER }}/thesnaxers:latest
        docker tag thesnaxers:latest ${{ secrets.ACR_LOGIN_SERVER }}/thesnaxers:${{ github.sha }}
        
        # Nu skickar vi upp båda versionerna till molnet
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/thesnaxers --all-tags